version: "3"
services:
  ubuntu-texlive-ja:
    # image: korosuke613/ubuntu-texlive-ja-devcontainer
    build: .
    command: sleep infinity
    volumes:
      - ../:/home/user/project
      - ~/.gitconfig:/home/user/.gitconfig
      - ./.latexmkrc:/home/user/.latexmkrc
    environment:
      SHELL: "/bin/bash"